name: TCNJ Magic Circle
title: TCNJ Magic Circle

baseurl:    /
future:     false
permalink:  /news/:year-:month-:day-:title/


news:
- title: This is a News Title
  desc: |
    This is a description of the news.  It's fancy.
- title: Moar News
  desc: |
    MOAAAR NEEEWS!


events:
- title: Global Game Jam 2014
  desc: |
    <a href="http://globalgamejam.org/about">The Global Game Jam</a> (GGJ) is the world's largest game jam event. Think of it as a hackathon focused on game development. It is the growth of an idea that in today’s heavily connected world, we could come together, be creative, share experiences and express ourselves in a multitude of ways using video games.  Magic Circle will be hosting a GGJ site at TCNJ.


projects:
- title: GUILT
  desc: |
    The player character is a bystander in the game world. By simply playing, the character witnesses things that are outside of their control. In fact, the character's presence alone can cause horrible events to occur. You may have a few choices throughout the game, but in the end, they are pointless.
  members: [Patrick D'Errico, Zach French, Matt King, Kyle Mesce]


eboard:
- title: President
  name: Alexa Cain
  bio: |
    Alexa Cain is a snior Computer Science major. She has been an active member of the club since she accidentally stumbled into the pre-semester planning meeting fall of her freshman year. She loves the theory of game design and psychology of play. She also thoroughly enjoys playtesting, possibly because she is excellent at breaking everything.
  link: http://www.tcnj.edu/~caina1/applet/
- title: Vice President
  name: Teddy Sudol
  bio: |
    Teddy Sudol is a senior Computer Science major/Music minor. He joined the club in the Spring 2011 semester with the Painter Lee project. Teddy brings a strong programming background to his projects, but hopes to move into other areas such as music. He looks forward to expanding the Magic Circle club with new projects, events and ideas.
  link: http://tsudol.com/
- title: Secretary
  name: Glen Oakley
  bio: |
    Glen Oakley is a senior Computer Science major. He has been a member of Magic Circle since his first year at TCNJ. He is excited to help make the club better than ever as both a board member and a skilled programmer, and has a few casual game projects under his belt. Glen is also a board member of TCNJ's ACM. Glen's favorite pony is Rarity.
  link: http://glenoakley.com/
- title: Treasurer
  name: Kyle Mesce
  bio: |
    Kyle is a senior Applied Mathematics major and music minor. He has been with Magic Circle since Fall 2011, but became much more involved when the GUILT project came around. Mainly, he is interested in the artistic value of games, especially the music. Kyle still believes EVERYONE should play Mother 3.
  link: http://www.tcnj.edu/~mescek1/
- title: Publicist
  name: Steve Boyland
  bio: |
    After stumbling into the very first Magic Circle meeting in Spring 2010 expecting free snacks (there were none), Steve has despite all odds stuck around to become the club Publicist for the second year in a row. A graphic designer and artist by trade, Steve keeps busy not doing any of that and browsing sports forums instead. Steve very much enjoys the creative process on the rare occasions when he does not completely hate the creative process. He is still waiting for the free snacks.
  link: http://www.steveboyland.com/
- title: Webmaster
  name: Tim Honeywell
  bio: |
    Tim Honeywell is a graduate, holding a dual major in Computer Science and Interactive Multimedia. He is one of the charter members of the club, but wasn't heavily involved until he started the GRACE project in Fall 2011. Tim is unapologetically interested in far too many subjects: AI, graphics, music, game theory, efficiency, and human-computer interaction. He may not be an expert in anything, but he knows how to bring the experts together and get them to make pretty things.
  link: http://tfhoneywell.com/


resources:
- title: HTML5 Game Development
  blurb: An online course in which you will take standard game development techniques and use them to create high performance HTML5 applications
  link: https://www.udacity.com/course/cs255
- title: One Game A Month
  blurb: Starting a game is easy - Finishing a game is hard - Your quest is to create one game each month for the rest of 2013
  link: http://www.onegameamonth.com/
