title: TCNJ Magic Circle

baseurl:    /
future:     false
permalink:  /news/:year-:month-:day-:title/



eboard:
- title: President
  name: Alexa Cain
  bio: |
    Alexa Cain is.
  external: http://www.tcnj.edu/~caina1/applet/
- title: Vice President
  name: Bobby Canciello
  bio: |
    Bobby Canciello is a senior Interactive Multimedia major/Digital Art minor. An original charter member, his love for game design was awakened upon attending his first Global Game Jam in 2011. Considering himself neither pure artist nor programmer, he prefers to walk the line between the two, using his interpersonal and managerial skills to efficiently lead and solidify a group. Though his passion lies in environment creation, he loves nothing more than being in the thick of production—brainstorming mechanics, modeling assets, generating design documents, and guiding a swarm of creative possibilities into one cohesive vision.
  external: http://www.bobbycanciellointeractivedesign.weebly.com/
- title: Secretary
  name: Glen Oakley
  bio: |
    Glen Oakley is a junior Computer Science major. He has been a member of Magic Circle since his first year at TCNJ. He is excited to help make the club better than ever as both a board member and a skilled programmer. Glen is also a board member of TCNJ's ACM. Glen's favorite pony is Rarity.
  external: http://goakley.github.com/
- title: Treasurer
  name: Teddy Sudol
  bio: |
    Teddy Sudol is a junior Computer Science major/Music minor. He joined the club in the Spring 2011 semester with the Painter Lee project. Teddy brings a strong programming background to his projects, but hopes to move into other areas such as music. He looks forward to expanding the Magic Circle club with new projects, events and ideas.
  external: http://tsudol.com/
- title: Publicist
  name: Steve Boyland
  bio: |
    After stumbling into the very first Magic Circle meeting in Spring 2010 expecting free snacks (there were none), Steve has despite all odds stuck around to become the club Publicist for the second year in a row. A graphic designer and artist by trade, Steve keeps busy not doing any of that and browsing sports forums instead. Steve very much enjoys the creative process on the rare occasions when he does not completely hate the creative process. He is still waiting for the free snacks.
  external: http://www.steveboyland.com/
- title: Webmaster
  name: Tim Honeywell
  bio: |
    Tim Honeywell is a senior pursuing a dual major in Computer Science and Interactive Multimedia. He is one of the charter members of the club, but wasn't heavily involved until he started the GRACE project in fall 2011. Tim is unapologetically interested in far too many subjects: AI, graphics, music, game theory, efficiency, and human-computer interaction. He may not be an expert in anything, but he knows how to bring the experts together and get them to make pretty things.
  external: http://tfhoneywell.com/



navigation:
- title: News
  url: /news/
  glyph: icon-inbox
- title: Events
  url: /events/
  glyph: icon-calendar
- title: People
  url: /people/
  glyph: icon-user
- title: Projects
  url: /projects/
  glyph: icon-road
- title: Resources
  url: /resources/
  glyph: icon-book
- title: Contact
  url: /contact/
  glyph: icon-envelope
