title: TCNJ Magic Circle

baseurl:    /
future:     false
permalink:  /news/:year-:month-:day-:title/


navigation:
- title: Home
  url: /
- title: News
  url: /news/
- title: Events
  url: /events/
- title: People
  url: /people/
- title: Projects
  url: /projects/
- title: Resources
  url: /resources/
- title: Contact
  url: /contact/
